/* eslint-disable @next/next/no-css-tags */
import Head from "next/head";
import LayoutClient from "../layouts/LayoutClient";
import BannerTop from "../Components/HomeComponents/BannerTop";
import CoQuanVaGioiThieu from "../Components/HomeComponents/CoQuanVaGioiThieu";
import ThongKeNhanh from "../Components/HomeComponents/ThongKeNhanh";
import DangKyHienTang from "../Components/HomeComponents/DangKyHienTang";
import ThongTinTruyenThong from "../Components/HomeComponents/ThongTinTruyenThong";
import CauHoiThuongGap from "../Components/HomeComponents/CauHoiThuongGap";
import ThongTinYKhoa from "../Components/HomeComponents/ThongTinYKhoa";
// import MessengerCustomerChat from '../Components/react-messenger-customer-chat';
import MessengerCustomerChat from "react-messenger-customer-chat";

function Home() {
  return (
    <div>
      <>
        <Head>
          <title>Cổng đăng ký hiến và ghép mô tạng - Bệnh viện Chợ Rẫy</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="title"
            content="Cổng đăng ký hiến và ghép tạng - Bệnh viện Chợ Rẫy"
          />
          <meta name="description" content="Hinet JSC" />

          <link rel="icon" href="/favicon.ico" />
          <link href="/libs/fontawesome/css/all.css" rel="stylesheet"></link>
        </Head>
      </>
      <div>
        <BannerTop />
        <CoQuanVaGioiThieu />
        <ThongKeNhanh />
        <ThongTinYKhoa />
        <DangKyHienTang />
        <ThongTinTruyenThong />
        <CauHoiThuongGap />
        <MessengerCustomerChat
           pageId="503486866782616"
           appId="403668491128518"
          // htmlRef="<REF_STRING>"
          //pageId="141259733037430"
          //appId="479802529808660"
          // htmlRef="http://hoanvx.hihihaha.biz/"
          //htmlRef="<REF_STRING>"
          htmlRef="/"
        />
      </div>
    </div>
  );
}
Home.getLayout = function getLayout(page) {
  return <LayoutClient>{page}</LayoutClient>;
};
export default Home;
